# Generated by Django 3.2.7 on 2021-09-23 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='active',
            field=models.BooleanField(default=False, verbose_name=False),
            preserve_default=False,
        ),
    ]
