listWindow = {
    'pwd' : "print working directory",
    'hostname': "my computer’s network name",
    'mkdir': 'make directory',
    'cd': 'change directory',
    'ls': 'list directory',
    'rmdir': 'remove directory',
    'pushd': 'push directory',
    'popd': 'pop directory',
    'cp': 'copy a fi le or directory',
    'robocopy': "robust copy",
    'mv': 'move a fi le or directory',
    'more': 'page through a fi le',
    'type': 'print the whole fi le',
    'forfi': 'les run a command on lots of files',
    'dir': '- r fi nd fi les',
    'select': '- string fi nd things inside files',
    'help': 'read a manual page',
    'helpctr': 'find what man page is appropriate',
    'echo': 'print some arguments',
    'set': 'export/set a new environment variable',
    'exit': 'exit the shell',
    'runas': 'DANGER! become super user root DANGER!'
}
